# cargo-features = [ "strip" ]

[workspace]
members = [
	"bee-api/bee-rest-api",
	"bee-node",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[profile.production]
codegen-units = 1
inherits = "release"
lto = true
panic = "abort"
# strip = "symbols"
